steps:
  - name: "python:3.12-slim"
    id: install-dependencies
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        pip install uv==0.8.13 --user && uv sync --locked
    env:
      - 'PATH=/usr/local/bin:/usr/bin:~/.local/bin'

  - name: "python:3.12-slim"
    id: deploy
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        uv export --no-hashes --no-sources --no-header --no-dev \
          --no-emit-project --no-annotate --locked \
          > google_trends_agent/app_utils/.requirements.txt

        uv run python -m google_trends_agent.app_utils.deploy \
          --project ${_PROJECT_ID} \
          --location ${_REGION} \
          --source-packages=./google_trends_agent \
          --entrypoint-module=google_trends_agent.agent_engine_app \
          --entrypoint-object=agent_engine \
          --requirements-file=google_trends_agent/app_utils/.requirements.txt \
          --service-account=${_APP_SERVICE_ACCOUNT} \
          --set-env-vars="COMMIT_SHA=${COMMIT_SHA},LOGS_BUCKET_NAME=${_LOGS_BUCKET_NAME}"
    env:
      - 'PATH=/usr/local/bin:/usr/bin:~/.local/bin'

substitutions:
  _PROJECT_ID: ge-bootcamp26lis-902
  _REGION: europe-west1
  _LOGS_BUCKET_NAME: ""
  _APP_SERVICE_ACCOUNT: ""

logsBucket: gs://${_LOGS_BUCKET_NAME}/build-logs
options:
  substitutionOption: ALLOW_LOOSE
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
